config/routes.rb
Rails.application.routes.draw do
  resources :asignaturas
  resources :estudiantes
  resources :profesors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignatura.rb
class Asignatura < ApplicationRecord
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
end

app/models/profesor.rb
class Profesor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  before_action :set_asignatura, only: [:show, :edit, :update, :destroy]

  # GET /asignaturas
  # GET /asignaturas.json
  def index
    @asignaturas = Asignatura.all
  end

  # GET /asignaturas/1
  # GET /asignaturas/1.json
  def show
  end

  # GET /asignaturas/new
  def new
    @asignatura = Asignatura.new
  end

  # GET /asignaturas/1/edit
  def edit
  end

  # POST /asignaturas
  # POST /asignaturas.json
  def create
    @asignatura = Asignatura.new(asignatura_params)

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully created.' }
        format.json { render :show, status: :created, location: @asignatura }
      else
        format.html { render :new }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignaturas/1
  # PATCH/PUT /asignaturas/1.json
  def update
    respond_to do |format|
      if @asignatura.update(asignatura_params)
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully updated.' }
        format.json { render :show, status: :ok, location: @asignatura }
      else
        format.html { render :edit }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaturas/1
  # DELETE /asignaturas/1.json
  def destroy
    @asignatura.destroy
    respond_to do |format|
      format.html { redirect_to asignaturas_url, notice: 'Asignatura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura
      @asignatura = Asignatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignatura_params
      params.require(:asignatura).permit(:codigo, :nombre, :prerresquisitos, :profesor, :creditos, :descripcion)
    end
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:show, :edit, :update, :destroy]

  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully created.' }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1
  # PATCH/PUT /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: 'Estudiante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudiante_params
      params.require(:estudiante).permit(:nombre, :birthday, :mail, :papa, :creditos_inscritos)
    end
end

app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]

  # GET /profesors
  # GET /profesors.json
  def index
    @profesors = Profesor.all
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
  end

  # GET /profesors/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesors/1/edit
  def edit
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new(profesor_params)

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render :show, status: :created, location: @profesor }
      else
        format.html { render :new }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesors/1
  # PATCH/PUT /profesors/1.json
  def update
    respond_to do |format|
      if @profesor.update(profesor_params)
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @profesor }
      else
        format.html { render :edit }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor.destroy
    respond_to do |format|
      format.html { redirect_to profesors_url, notice: 'Profesor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:name, :birthdate, :lastname, :mail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/views/asignaturas/_form.html.erb
<%= form_with(model: asignatura, local: true) do |form| %>
  <% if asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asignatura.errors.count, "error") %> prohibited this asignatura from being saved:</h2>

      <ul>
      <% asignatura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.number_field :codigo, id: :asignatura_codigo %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :asignatura_nombre %>
  </div>

  <div class="field">
    <%= form.label :prerresquisitos %>
    <%= form.check_box :prerresquisitos, id: :asignatura_prerresquisitos %>
  </div>

  <div class="field">
    <%= form.label :profesor %>
    <%= form.text_field :profesor, id: :asignatura_profesor %>
  </div>

  <div class="field">
    <%= form.label :creditos %>
    <%= form.number_field :creditos, id: :asignatura_creditos %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :asignatura_descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/asignaturas/edit.html.erb
<h1>Editing Asignatura</h1>

<%= render 'form', asignatura: @asignatura %>

<%= link_to 'Show', @asignatura %> |
<%= link_to 'Back', asignaturas_path %>

app/views/asignaturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asignaturas</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Prerresquisitos</th>
      <th>Profesor</th>
      <th>Creditos</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asignaturas.each do |asignatura| %>
      <tr>
        <td><%= asignatura.codigo %></td>
        <td><%= asignatura.nombre %></td>
        <td><%= asignatura.prerresquisitos %></td>
        <td><%= asignatura.profesor %></td>
        <td><%= asignatura.creditos %></td>
        <td><%= asignatura.descripcion %></td>
        <td><%= link_to 'Show', asignatura %></td>
        <td><%= link_to 'Edit', edit_asignatura_path(asignatura) %></td>
        <td><%= link_to 'Destroy', asignatura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asignatura', new_asignatura_path %>

app/views/asignaturas/new.html.erb
<h1>New Asignatura</h1>

<%= render 'form', asignatura: @asignatura %>

<%= link_to 'Back', asignaturas_path %>

app/views/asignaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @asignatura.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @asignatura.nombre %>
</p>

<p>
  <strong>Prerresquisitos:</strong>
  <%= @asignatura.prerresquisitos %>
</p>

<p>
  <strong>Profesor:</strong>
  <%= @asignatura.profesor %>
</p>

<p>
  <strong>Creditos:</strong>
  <%= @asignatura.creditos %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @asignatura.descripcion %>
</p>

<%= link_to 'Edit', edit_asignatura_path(@asignatura) %> |
<%= link_to 'Back', asignaturas_path %>

app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante, local: true) do |form| %>
  <% if estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
      <% estudiante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :estudiante_nombre %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :estudiante_birthday %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail, id: :estudiante_mail %>
  </div>

  <div class="field">
    <%= form.label :papa %>
    <%= form.text_field :papa, id: :estudiante_papa %>
  </div>

  <div class="field">
    <%= form.label :creditos_inscritos %>
    <%= form.text_field :creditos_inscritos, id: :estudiante_creditos_inscritos %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estudiantes/edit.html.erb
<h1>Editing Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Show', @estudiante %> |
<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Birthday</th>
      <th>Mail</th>
      <th>Papa</th>
      <th>Creditos inscritos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.nombre %></td>
        <td><%= estudiante.birthday %></td>
        <td><%= estudiante.mail %></td>
        <td><%= estudiante.papa %></td>
        <td><%= estudiante.creditos_inscritos %></td>
        <td><%= link_to 'Show', estudiante %></td>
        <td><%= link_to 'Edit', edit_estudiante_path(estudiante) %></td>
        <td><%= link_to 'Destroy', estudiante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estudiante', new_estudiante_path %>

app/views/estudiantes/new.html.erb
<h1>New Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estudiante.nombre %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @estudiante.birthday %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @estudiante.mail %>
</p>

<p>
  <strong>Papa:</strong>
  <%= @estudiante.papa %>
</p>

<p>
  <strong>Creditos inscritos:</strong>
  <%= @estudiante.creditos_inscritos %>
</p>

<%= link_to 'Edit', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Back', estudiantes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taller2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profesors/_form.html.erb
<%= form_with(model: profesor, local: true) do |form| %>
  <% if profesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profesor.errors.count, "error") %> prohibited this profesor from being saved:</h2>

      <ul>
      <% profesor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :profesor_name %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate, id: :profesor_birthdate %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :profesor_lastname %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail, id: :profesor_mail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profesors/edit.html.erb
<h1>Editing Profesor</h1>

<%= render 'form', profesor: @profesor %>

<%= link_to 'Show', @profesor %> |
<%= link_to 'Back', profesors_path %>

app/views/profesors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profesors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthdate</th>
      <th>Lastname</th>
      <th>Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesors.each do |profesor| %>
      <tr>
        <td><%= profesor.name %></td>
        <td><%= profesor.birthdate %></td>
        <td><%= profesor.lastname %></td>
        <td><%= profesor.mail %></td>
        <td><%= link_to 'Show', profesor %></td>
        <td><%= link_to 'Edit', edit_profesor_path(profesor) %></td>
        <td><%= link_to 'Destroy', profesor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profesor', new_profesor_path %>

app/views/profesors/new.html.erb
<h1>New Profesor</h1>

<%= render 'form', profesor: @profesor %>

<%= link_to 'Back', profesors_path %>

app/views/profesors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profesor.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @profesor.birthdate %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profesor.lastname %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @profesor.mail %>
</p>

<%= link_to 'Edit', edit_profesor_path(@profesor) %> |
<%= link_to 'Back', profesors_path %>